#!/usr/bin/env bash
set -e

if [[ "$VIRTUAL_ENV" == "" ]]; then
    echo "You may not be in virtualenv. Try activate virtualenv first."
    exit 1;
fi

if [[ "$TEST_DATABASE_URL" == "" ]]; then
    echo "TEST_DATABASE_URL is not configured."
    exit 1;
fi
pytest
